### ISSUE TITLE
Test Suite not passing on Travis

### ISSUE THREAD

**Issue by DamonOehlman** [DamonOehlman/sharedconfig#1]
While this is currently impacted by iriscouch/follow#13 I seem to be hitting document update conflicts before I even get to that point.  Must investigate.

**Comment by coen-hyde** [comment]
You bet me to the punch by a few mins on dscape/nano#144

**Comment by DamonOehlman** [comment]
lol :)

**Comment by dscape** [comment]
New version released :) 

Check it out. Thanks guys!

**Comment by DamonOehlman** [comment]
Thanks mate :)

**Comment by DamonOehlman** [comment]
Closing this issue but getting inconsistent results when running tests, tracking that issue at #6.
